name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure CMake
      working-directory: ./build
      run: cmake ..
    
    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release
    
    - name: Run It!
      working-directory: ./build
      run: ./string_impl ../TestData.txt